-- ============================================================
-- 001_product_ecommerce_columns.sql  (SQL Server)
-- Agrega columnas ecommerce faltantes a master.Product
-- Idempotente: verifica existencia antes de agregar
-- ============================================================

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='master' AND TABLE_NAME='Product' AND COLUMN_NAME='LongDescription')
    ALTER TABLE master.Product ADD LongDescription NVARCHAR(MAX) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='master' AND TABLE_NAME='Product' AND COLUMN_NAME='WeightKg')
    ALTER TABLE master.Product ADD WeightKg DECIMAL(10,3) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='master' AND TABLE_NAME='Product' AND COLUMN_NAME='WidthCm')
    ALTER TABLE master.Product ADD WidthCm DECIMAL(10,2) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='master' AND TABLE_NAME='Product' AND COLUMN_NAME='HeightCm')
    ALTER TABLE master.Product ADD HeightCm DECIMAL(10,2) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='master' AND TABLE_NAME='Product' AND COLUMN_NAME='DepthCm')
    ALTER TABLE master.Product ADD DepthCm DECIMAL(10,2) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='master' AND TABLE_NAME='Product' AND COLUMN_NAME='WarrantyMonths')
    ALTER TABLE master.Product ADD WarrantyMonths INT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='master' AND TABLE_NAME='Product' AND COLUMN_NAME='BarCode')
    ALTER TABLE master.Product ADD BarCode NVARCHAR(50) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='master' AND TABLE_NAME='Product' AND COLUMN_NAME='Slug')
    ALTER TABLE master.Product ADD Slug NVARCHAR(200) NULL;
GO
