SET NOCOUNT ON;

IF OBJECT_ID('[dbo].[DtllAsiento]','V') IS NOT NULL BEGIN DROP VIEW [dbo].[DtllAsiento]; PRINT 'Dropped VIEW [dbo].[DtllAsiento]'; END
IF OBJECT_ID('[dbo].[sp_anular_compra_tx]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[sp_anular_compra_tx]; PRINT 'Dropped PROC [dbo].[sp_anular_compra_tx]'; END
IF OBJECT_ID('[dbo].[sp_anular_factura_tx]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[sp_anular_factura_tx]; PRINT 'Dropped PROC [dbo].[sp_anular_factura_tx]'; END
IF OBJECT_ID('[dbo].[sp_anular_presupuesto_tx]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[sp_anular_presupuesto_tx]; PRINT 'Dropped PROC [dbo].[sp_anular_presupuesto_tx]'; END
IF OBJECT_ID('[dbo].[sp_emitir_compra_tx]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[sp_emitir_compra_tx]; PRINT 'Dropped PROC [dbo].[sp_emitir_compra_tx]'; END
IF OBJECT_ID('[dbo].[sp_emitir_cotizacion_tx]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[sp_emitir_cotizacion_tx]; PRINT 'Dropped PROC [dbo].[sp_emitir_cotizacion_tx]'; END
IF OBJECT_ID('[dbo].[sp_emitir_factura_tx]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[sp_emitir_factura_tx]; PRINT 'Dropped PROC [dbo].[sp_emitir_factura_tx]'; END
IF OBJECT_ID('[dbo].[sp_emitir_presupuesto_tx]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[sp_emitir_presupuesto_tx]; PRINT 'Dropped PROC [dbo].[sp_emitir_presupuesto_tx]'; END
IF OBJECT_ID('[dbo].[usp_Clientes_Delete]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Clientes_Delete]; PRINT 'Dropped PROC [dbo].[usp_Clientes_Delete]'; END
IF OBJECT_ID('[dbo].[usp_Clientes_GetByCodigo]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Clientes_GetByCodigo]; PRINT 'Dropped PROC [dbo].[usp_Clientes_GetByCodigo]'; END
IF OBJECT_ID('[dbo].[usp_Clientes_Insert]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Clientes_Insert]; PRINT 'Dropped PROC [dbo].[usp_Clientes_Insert]'; END
IF OBJECT_ID('[dbo].[usp_Clientes_List]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Clientes_List]; PRINT 'Dropped PROC [dbo].[usp_Clientes_List]'; END
IF OBJECT_ID('[dbo].[usp_Clientes_Update]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Clientes_Update]; PRINT 'Dropped PROC [dbo].[usp_Clientes_Update]'; END
IF OBJECT_ID('[dbo].[usp_Compras_GetByNumFact]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Compras_GetByNumFact]; PRINT 'Dropped PROC [dbo].[usp_Compras_GetByNumFact]'; END
IF OBJECT_ID('[dbo].[usp_Compras_List]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Compras_List]; PRINT 'Dropped PROC [dbo].[usp_Compras_List]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Ajuste_Crear]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Ajuste_Crear]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Ajuste_Crear]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Asiento_Anular]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Asiento_Anular]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Asiento_Anular]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Asiento_Crear]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Asiento_Crear]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Asiento_Crear]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Asiento_Get]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Asiento_Get]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Asiento_Get]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Asientos_List]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Asientos_List]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Asientos_List]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Balance_Comprobacion]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Balance_Comprobacion]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Balance_Comprobacion]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Balance_General]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Balance_General]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Balance_General]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Depreciacion_Generar]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Depreciacion_Generar]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Depreciacion_Generar]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Estado_Resultados]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Estado_Resultados]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Estado_Resultados]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Libro_Mayor]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Libro_Mayor]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Libro_Mayor]'; END
IF OBJECT_ID('[dbo].[usp_Contabilidad_Mayor_Analitico]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Contabilidad_Mayor_Analitico]; PRINT 'Dropped PROC [dbo].[usp_Contabilidad_Mayor_Analitico]'; END
IF OBJECT_ID('[dbo].[usp_Cotizacion_GetByNumFact]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Cotizacion_GetByNumFact]; PRINT 'Dropped PROC [dbo].[usp_Cotizacion_GetByNumFact]'; END
IF OBJECT_ID('[dbo].[usp_Cotizacion_List]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Cotizacion_List]; PRINT 'Dropped PROC [dbo].[usp_Cotizacion_List]'; END
IF OBJECT_ID('[dbo].[usp_Cuentas_Delete]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Cuentas_Delete]; PRINT 'Dropped PROC [dbo].[usp_Cuentas_Delete]'; END
IF OBJECT_ID('[dbo].[usp_Cuentas_GetByCodigo]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Cuentas_GetByCodigo]; PRINT 'Dropped PROC [dbo].[usp_Cuentas_GetByCodigo]'; END
IF OBJECT_ID('[dbo].[usp_Cuentas_Insert]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Cuentas_Insert]; PRINT 'Dropped PROC [dbo].[usp_Cuentas_Insert]'; END
IF OBJECT_ID('[dbo].[usp_Cuentas_List]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Cuentas_List]; PRINT 'Dropped PROC [dbo].[usp_Cuentas_List]'; END
IF OBJECT_ID('[dbo].[usp_Cuentas_Update]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Cuentas_Update]; PRINT 'Dropped PROC [dbo].[usp_Cuentas_Update]'; END
IF OBJECT_ID('[dbo].[usp_Empleados_Delete]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Empleados_Delete]; PRINT 'Dropped PROC [dbo].[usp_Empleados_Delete]'; END
IF OBJECT_ID('[dbo].[usp_Empleados_GetByCedula]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Empleados_GetByCedula]; PRINT 'Dropped PROC [dbo].[usp_Empleados_GetByCedula]'; END
IF OBJECT_ID('[dbo].[usp_Empleados_Insert]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Empleados_Insert]; PRINT 'Dropped PROC [dbo].[usp_Empleados_Insert]'; END
IF OBJECT_ID('[dbo].[usp_Empleados_List]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Empleados_List]; PRINT 'Dropped PROC [dbo].[usp_Empleados_List]'; END
IF OBJECT_ID('[dbo].[usp_Empleados_Update]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Empleados_Update]; PRINT 'Dropped PROC [dbo].[usp_Empleados_Update]'; END
IF OBJECT_ID('[dbo].[usp_Facturas_GetByNumFact]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Facturas_GetByNumFact]; PRINT 'Dropped PROC [dbo].[usp_Facturas_GetByNumFact]'; END
IF OBJECT_ID('[dbo].[usp_Facturas_List]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Facturas_List]; PRINT 'Dropped PROC [dbo].[usp_Facturas_List]'; END
IF OBJECT_ID('[dbo].[usp_Inventario_Delete]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Inventario_Delete]; PRINT 'Dropped PROC [dbo].[usp_Inventario_Delete]'; END
IF OBJECT_ID('[dbo].[usp_Inventario_GetByCodigo]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Inventario_GetByCodigo]; PRINT 'Dropped PROC [dbo].[usp_Inventario_GetByCodigo]'; END
IF OBJECT_ID('[dbo].[usp_Inventario_Insert]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Inventario_Insert]; PRINT 'Dropped PROC [dbo].[usp_Inventario_Insert]'; END
IF OBJECT_ID('[dbo].[usp_Inventario_List]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Inventario_List]; PRINT 'Dropped PROC [dbo].[usp_Inventario_List]'; END
IF OBJECT_ID('[dbo].[usp_Inventario_Update]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Inventario_Update]; PRINT 'Dropped PROC [dbo].[usp_Inventario_Update]'; END
IF OBJECT_ID('[dbo].[usp_Pedidos_GetByNumFact]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Pedidos_GetByNumFact]; PRINT 'Dropped PROC [dbo].[usp_Pedidos_GetByNumFact]'; END
IF OBJECT_ID('[dbo].[usp_Pedidos_List]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Pedidos_List]; PRINT 'Dropped PROC [dbo].[usp_Pedidos_List]'; END
IF OBJECT_ID('[dbo].[usp_Proveedores_Delete]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Proveedores_Delete]; PRINT 'Dropped PROC [dbo].[usp_Proveedores_Delete]'; END
IF OBJECT_ID('[dbo].[usp_Proveedores_GetByCodigo]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Proveedores_GetByCodigo]; PRINT 'Dropped PROC [dbo].[usp_Proveedores_GetByCodigo]'; END
IF OBJECT_ID('[dbo].[usp_Proveedores_Insert]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Proveedores_Insert]; PRINT 'Dropped PROC [dbo].[usp_Proveedores_Insert]'; END
IF OBJECT_ID('[dbo].[usp_Proveedores_List]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Proveedores_List]; PRINT 'Dropped PROC [dbo].[usp_Proveedores_List]'; END
IF OBJECT_ID('[dbo].[usp_Proveedores_Update]','P') IS NOT NULL BEGIN DROP PROCEDURE [dbo].[usp_Proveedores_Update]; PRINT 'Dropped PROC [dbo].[usp_Proveedores_Update]'; END
