SET NOCOUNT ON;
GO

USE master;
GO

IF DB_ID(N'DatqBoxWeb') IS NULL
BEGIN
  PRINT 'Creating DatqBoxWeb database...';
  CREATE DATABASE DatqBoxWeb;
END
ELSE
BEGIN
  PRINT 'DatqBoxWeb already exists.';
END
GO

ALTER DATABASE DatqBoxWeb SET COMPATIBILITY_LEVEL = 110;
GO

-- Modern SQL defaults for deterministic behavior (SQL Server 2012 compatible)
ALTER DATABASE DatqBoxWeb SET ANSI_NULL_DEFAULT ON;
ALTER DATABASE DatqBoxWeb SET ANSI_NULLS ON;
ALTER DATABASE DatqBoxWeb SET ANSI_PADDING ON;
ALTER DATABASE DatqBoxWeb SET ANSI_WARNINGS ON;
ALTER DATABASE DatqBoxWeb SET ARITHABORT ON;
ALTER DATABASE DatqBoxWeb SET CONCAT_NULL_YIELDS_NULL ON;
ALTER DATABASE DatqBoxWeb SET QUOTED_IDENTIFIER ON;
ALTER DATABASE DatqBoxWeb SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE DatqBoxWeb SET AUTO_CLOSE OFF;
ALTER DATABASE DatqBoxWeb SET AUTO_SHRINK OFF;
ALTER DATABASE DatqBoxWeb SET AUTO_CREATE_STATISTICS ON;
ALTER DATABASE DatqBoxWeb SET AUTO_UPDATE_STATISTICS ON;
GO

PRINT 'DatqBoxWeb initialized with standard settings.';
GO
