import type { DesignTokens } from './types';

/**
 * Genera un string CSS con las variables de diseño a partir del
 * `designTokens` TypeScript object.
 *
 * Produce:
 *   :root                        → variables del esquema light.
 *   [data-theme="dark"]
 *   [data-toolpad-color-scheme]
 *   .dark                        → variables del esquema dark.
 *
 * Tailwind v4 puede consumirlas directamente con
 *   @theme { --color-primary: var(--zentto-color-primary); }
 * o referenciarlas inline con utilities `bg-[var(--zentto-color-primary)]`.
 */
export function tokensToCss(tokens: DesignTokens): string {
  const lightVars = buildVars(tokens, 'light');
  const darkVars = buildVars(tokens, 'dark');

  return [
    '/* Generated by @zentto/design-tokens — do not edit by hand. */',
    ':root {',
    ...lightVars.map((l) => `  ${l}`),
    '}',
    '',
    '[data-theme="dark"],',
    '[data-toolpad-color-scheme="dark"],',
    '.dark {',
    ...darkVars.map((l) => `  ${l}`),
    '}',
    '',
  ].join('\n');
}

function buildVars(tokens: DesignTokens, scheme: 'light' | 'dark'): string[] {
  const lines: string[] = [];

  // Color — palette roles.
  const palette = tokens.color[scheme];
  (['primary', 'secondary', 'success', 'warning', 'error', 'info'] as const).forEach((role) => {
    const c = palette[role];
    lines.push(`--zentto-color-${role}: ${c.main};`);
    lines.push(`--zentto-color-${role}-light: ${c.light};`);
    lines.push(`--zentto-color-${role}-dark: ${c.dark};`);
    lines.push(`--zentto-color-${role}-contrast: ${c.contrastText};`);
  });

  // Color — scheme surfaces.
  const sc = palette.scheme;
  lines.push(`--zentto-color-background: ${sc.background};`);
  lines.push(`--zentto-color-surface: ${sc.surface};`);
  lines.push(`--zentto-color-text: ${sc.text};`);
  lines.push(`--zentto-color-text-secondary: ${sc.textSecondary};`);
  lines.push(`--zentto-color-divider: ${sc.divider};`);

  // Scheme-agnostic tokens emitted once (en :root) para no duplicar.
  if (scheme === 'light') {
    Object.entries(tokens.brand).forEach(([k, v]) => {
      lines.push(`--zentto-brand-${kebab(k)}: ${v};`);
    });

    lines.push(`--zentto-spacing-section-gap: ${tokens.layout.sectionGap}px;`);
    lines.push(`--zentto-spacing-form-gap: ${tokens.layout.formGap}px;`);
    lines.push(`--zentto-spacing-chip-gap: ${tokens.layout.chipGap}px;`);

    lines.push(`--zentto-density-row-compact: ${tokens.density.rowHeight.compact}px;`);
    lines.push(`--zentto-density-row-default: ${tokens.density.rowHeight.default}px;`);
    lines.push(`--zentto-density-row-comfortable: ${tokens.density.rowHeight.comfortable}px;`);
    lines.push(`--zentto-density-header: ${tokens.density.columnHeaderHeight}px;`);

    lines.push(`--zentto-font-family: ${tokens.typography.fontFamily};`);
    Object.entries(tokens.typography.roles).forEach(([role, meta]) => {
      lines.push(`--zentto-font-size-${role}: ${meta.size};`);
      lines.push(`--zentto-font-weight-${role}: ${meta.weight};`);
      lines.push(`--zentto-line-height-${role}: ${meta.lineHeight};`);
    });

    Object.entries(tokens.radius).forEach(([k, v]) => {
      lines.push(`--zentto-radius-${k}: ${typeof v === 'number' ? `${v}px` : v};`);
    });

    Object.entries(tokens.elevation).forEach(([k, v]) => {
      lines.push(`--zentto-elevation-${k}: ${v};`);
    });

    Object.entries(tokens.zIndex).forEach(([k, v]) => {
      lines.push(`--zentto-z-${kebab(k)}: ${v};`);
    });
  }

  return lines;
}

function kebab(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}
