-- =============================================
-- Seed completo: constantes + todos los gananciales y deducciones por convenio
-- Incluye: horas extras, descanso trabajado, feriados trabajados, tiempo de viaje,
-- comidas/TEA, vivienda; FAOV/SSO sobre total devengado (base legal habitacional).
-- Variables usadas: SUELDO, SALARIO_DIARIO, SALARIO_HORA, TOTAL_ASIGNACIONES, HORAS_EXTRAS,
-- FERIADOS_TRABAJADOS, DOMINGOS_TRABAJADOS, DIAS_TIEMPO_VIAJE, DIAS_COMIDA, etc.
-- =============================================

SET NOCOUNT ON;

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ConstanteNomina')
BEGIN
    CREATE TABLE dbo.ConstanteNomina (
        Codigo  NVARCHAR(50) NOT NULL PRIMARY KEY,
        Nombre  NVARCHAR(150) NULL,
        Valor   FLOAT NULL,
        Origen  NVARCHAR(100) NULL
    );
END

-- Constantes: deducciones, dias, recargos (LOTTT / RPLOTTT)
MERGE dbo.ConstanteNomina AS t
USING (VALUES
    ('BaseUtil', N'Base utilidad % salario integral', 0, N'LOTTT'),
    ('TECHOSSO', N'Techo SSO (salarios minimos)', 5, N'LOTTT'),
    ('PCT_SSO', N'SSO trabajador %', 0.04, N'LOTTT'),
    ('PCT_FAOV', N'FAOV trabajador % (sobre devengado)', 0.01, N'Ley Vivienda'),
    ('PCT_LRPE', N'LRPE paro forzoso %', 0.005, N'LOTTT'),
    ('PCT_INCE_UTIL', N'INCE sobre utilidades %', 0.005, N'LOTTT'),
    ('DIAS_PRESTACION_ANIO', N'Prestaciones dias/ano', 30, N'LOTTT 142'),
    ('DIAS_PRESTACION_TRIM', N'Deposito trimestral dias', 15, N'LOTTT 142'),
    ('DIAS_VACACIONES_LOT', N'Vacaciones base ley', 15, N'LOTTT 189-203'),
    ('DIAS_BONO_VAC_LOT', N'Bono vacacional base ley', 15, N'LOTTT'),
    ('RECARGO_HE', N'Recargo horas extras % (0.5 = 50%)', 0.5, N'LOTTT 175-178'),
    ('RECARGO_FERIADO', N'Recargo feriado trabajado % (1 = 100%)', 1, N'LOTTT/RPLOTTT'),
    ('RECARGO_DESCANSO', N'Recargo descanso obligatorio trabajado % (1 = 100%)', 1, N'LOTTT/RPLOTTT'),
    ('RECARGO_NOCTURNO', N'Recargo hora nocturna % (0.3 = 30%)', 0.3, N'LOTTT'),
    ('HORAS_JORNADA', N'Horas jornada diurna', 8, N'LOTTT'),
    ('DIAS_LABORABLES_MES', N'Dias laborables referencia', 30, NULL),
    ('DIAS_VACACIONES_PETROLERO', N'Vacaciones CCT Petrolero', 34, N'CCP'),
    ('DIAS_BONO_VAC_PETROLERO', N'Bono vacacional CCT Petrolero', 55, N'CCP'),
    ('DIAS_BONO_POST_PETROLERO', N'Bono post-vacacional Petrolero', 15, N'CCP'),
    ('DIAS_UTILIDADES_PETROLERO', N'Utilidades base CCT Petrolero', 120, N'CCP'),
    ('DIAS_VACACIONES_CONSTRUCCION', N'Vacaciones CCT Construccion', 15, N'CCT'),
    ('DIAS_BONO_VAC_CONSTRUCCION', N'Bono vacacional CCT Construccion', 15, N'CCT'),
    ('MONTO_TEA_DIA', N'TEA/cesta ticket Bs por dia (parametrizable)', 0, N'LAT/LOTTT 190-194'),
    ('MONTO_COMIDA_DIA', N'Comidas Bs por dia (parametrizable)', 0, NULL),
    ('MONTO_VIVIENDA_DIA', N'Vivienda/ayuda habitacional Bs por dia', 0, N'LOTTT 159 CCP 23'),
    ('PORC_TIEMPO_VIAJE', N'% salario tiempo de viaje (0 a 1)', 0, N'CCT'),
    ('DIAS_UTILIDADES_LOT', N'Utilidades dias base ley', 30, N'LOTTT 131'),
    ('DIAS_UTILIDADES_CONSTRUCCION', N'Utilidades dias CCT Construccion', 30, N'CCT')
) AS s(Codigo, Nombre, Valor, Origen)
ON t.Codigo = s.Codigo
WHEN NOT MATCHED THEN INSERT (Codigo, Nombre, Valor, Origen) VALUES (s.Codigo, s.Nombre, s.Valor, s.Origen)
WHEN MATCHED THEN UPDATE SET t.Nombre = s.Nombre, t.Valor = s.Valor, t.Origen = s.Origen;

PRINT N'ConstanteNomina: constantes actualizadas.';

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'NominaConceptoLegal')
BEGIN
    RAISERROR('Ejecutar antes create_nomina_convencion_conocimiento.sql', 16, 1);
    RETURN;
END

-- Eliminar conceptos previos para reinsertar completos (mismo convenio/tipo)
DELETE FROM dbo.NominaConceptoLegal WHERE Convencion IN ('LOT','CCT_PETROLERO','CCT_CONSTRUCCION');

-- ========== LOT - MENSUAL: asignaciones gananciales + deducciones sobre devengado ==========
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, Orden)
VALUES
('LOT','MENSUAL','SUELDO',N'Sueldo base','SUELDO',NULL,'ASIGNACION','S',NULL,10),
('LOT','MENSUAL','HE',N'Horas extras','SALARIO_HORA * (1 + RECARGO_HE)','HORAS_EXTRAS','ASIGNACION','S',N'LOTTT 175-178',11),
('LOT','MENSUAL','HENOCT',N'Horas extras nocturnas','SALARIO_HORA * (1 + RECARGO_HE + RECARGO_NOCTURNO)','HORAS_EXTRAS_NOCTURNAS','ASIGNACION','S',N'LOTTT',12),
('LOT','MENSUAL','DESCTRAB',N'Descanso legal trabajado','SALARIO_DIARIO * (1 + RECARGO_DESCANSO)','DOMINGOS_TRABAJADOS','ASIGNACION','S',N'LOTTT/RPLOTTT',13),
('LOT','MENSUAL','FERIADTRAB',N'Feriado trabajado','SALARIO_DIARIO * (1 + RECARGO_FERIADO)','FERIADOS_TRABAJADOS','ASIGNACION','S',N'LOTTT',14),
('LOT','MENSUAL','TIEMVIAJE',N'Tiempo de viaje','SALARIO_DIARIO * PORC_TIEMPO_VIAJE','DIAS_TIEMPO_VIAJE','ASIGNACION','S',N'CCT',15),
('LOT','MENSUAL','TEA',N'TEA / Cesta ticket','MONTO_TEA_DIA','DIAS_PERIODO','ASIGNACION','N',N'LOTTT 190-194',16),
('LOT','MENSUAL','COMIDA',N'Comidas / Bono alimentacion','MONTO_COMIDA_DIA','DIAS_PERIODO','ASIGNACION','N',NULL,17),
('LOT','MENSUAL','SSO',N'SSO 4% (sobre devengado)','TOTAL_ASIGNACIONES * PCT_SSO',NULL,'DEDUCCION','N',N'LOTTT',100),
('LOT','MENSUAL','FAOV',N'FAOV 1% (sobre devengado)','TOTAL_ASIGNACIONES * PCT_FAOV',NULL,'DEDUCCION','N',N'Ley Vivienda',101),
('LOT','MENSUAL','LRPE',N'LRPE paro forzoso','TOTAL_ASIGNACIONES * PCT_LRPE',NULL,'DEDUCCION','N',N'LOTTT',102);

-- LOT - VACACIONES
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, Orden)
VALUES
('LOT','VACACIONES','VAC',N'Vacaciones','SALARIO_INTEGRAL','DIAS_VACACIONES','ASIGNACION','S',N'LOTTT 121',10),
('LOT','VACACIONES','BONOVAC',N'Bono vacacional','SALARIO_INTEGRAL','DIAS_BONO_VAC','ASIGNACION','S',N'LOTTT',11);

-- LOT - LIQUIDACION (FAOV/SSO sobre total asignaciones)
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, Orden)
VALUES
('LOT','LIQUIDACION','PREST',N'Prestaciones sociales','SALARIO_INTEGRAL','(ANTI_TOTAL_MESES / 12) * DIAS_PRESTACION_ANIO','ASIGNACION','N',N'LOTTT 142',10),
('LOT','LIQUIDACION','VACLIQ',N'Vacaciones no gozadas','SALARIO_INTEGRAL','DIAS_VACACIONES','ASIGNACION','N',N'LOTTT 192',11),
('LOT','LIQUIDACION','BONOVACLIQ',N'Bono vacacional liquidacion','SALARIO_INTEGRAL','DIAS_BONO_VAC','ASIGNACION','N',N'LOTTT',12),
('LOT','LIQUIDACION','SSOLIQ',N'SSO (sobre devengado)','TOTAL_ASIGNACIONES * PCT_SSO',NULL,'DEDUCCION','N',N'LOTTT',100),
('LOT','LIQUIDACION','FAOVLIQ',N'FAOV (sobre devengado)','TOTAL_ASIGNACIONES * PCT_FAOV',NULL,'DEDUCCION','N',N'Ley Vivienda',101);

-- ========== CCT PETROLERO - MENSUAL ==========
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, CCP_Clausula, Orden)
VALUES
('CCT_PETROLERO','MENSUAL','SUELDO',N'Sueldo base','SUELDO',NULL,'ASIGNACION','S',NULL,NULL,10),
('CCT_PETROLERO','MENSUAL','HE',N'Horas extras','SALARIO_HORA * (1 + RECARGO_HE)','HORAS_EXTRAS','ASIGNACION','S',N'LOTTT 178',N'CCP 24',11),
('CCT_PETROLERO','MENSUAL','HENOCT',N'Horas extras nocturnas','SALARIO_HORA * (1 + RECARGO_HE + RECARGO_NOCTURNO)','HORAS_EXTRAS_NOCTURNAS','ASIGNACION','S',N'LOTTT',NULL,12),
('CCT_PETROLERO','MENSUAL','DESCTRAB',N'Descanso trabajado','SALARIO_DIARIO * (1 + RECARGO_DESCANSO)','DOMINGOS_TRABAJADOS','ASIGNACION','S',N'LOTTT',NULL,13),
('CCT_PETROLERO','MENSUAL','FERIADTRAB',N'Feriado trabajado','SALARIO_DIARIO * (1 + RECARGO_FERIADO)','FERIADOS_TRABAJADOS','ASIGNACION','S',N'LOTTT',NULL,14),
('CCT_PETROLERO','MENSUAL','TIEMVIAJE',N'Tiempo de viaje','SALARIO_DIARIO * PORC_TIEMPO_VIAJE','DIAS_TIEMPO_VIAJE','ASIGNACION','S',N'CCP',NULL,15),
('CCT_PETROLERO','MENSUAL','TEA',N'TEA Tarjeta alimentacion','MONTO_TEA_DIA','DIAS_PERIODO','ASIGNACION','N',N'LOTTT 190-194',N'CCP 18',16),
('CCT_PETROLERO','MENSUAL','VIVIENDA',N'Vivienda ayuda habitacional','MONTO_VIVIENDA_DIA','DIAS_PERIODO','ASIGNACION','N',N'LOTTT 159',N'CCP 23',17),
('CCT_PETROLERO','MENSUAL','SSO',N'SSO (sobre devengado)','TOTAL_ASIGNACIONES * PCT_SSO',NULL,'DEDUCCION','N',N'LOTTT',NULL,100),
('CCT_PETROLERO','MENSUAL','FAOV',N'FAOV (sobre devengado)','TOTAL_ASIGNACIONES * PCT_FAOV',NULL,'DEDUCCION','N',N'Ley Vivienda',NULL,101),
('CCT_PETROLERO','MENSUAL','LRPE',N'LRPE','TOTAL_ASIGNACIONES * PCT_LRPE',NULL,'DEDUCCION','N',N'LOTTT',NULL,102);

-- CCT PETROLERO - VACACIONES
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, CCP_Clausula, Orden)
VALUES
('CCT_PETROLERO','VACACIONES','VAC',N'Vacaciones','SALARIO_INTEGRAL','DIAS_VACACIONES','ASIGNACION','S',N'LOTTT 121',N'CCP',10),
('CCT_PETROLERO','VACACIONES','VACAyu',N'Vacaciones ayuda','SALARIO_DIARIO','DIAS_VACACIONES * 1.62','ASIGNACION','S',N'LOTTT 157',N'CCP',11),
('CCT_PETROLERO','VACACIONES','BONOVAC',N'Bono vacacional','SALARIO_INTEGRAL','DIAS_BONO_VAC','ASIGNACION','S',N'LOTTT',N'CCP',12),
('CCT_PETROLERO','VACACIONES','BONOPOST',N'Bono post-vacacional','SALARIO_DIARIO','DIAS_BONO_POST_PETROLERO','ASIGNACION','S',N'LOTTT 157',N'CCP',13),
('CCT_PETROLERO','VACACIONES','TEA',N'TEA periodo vacacional','MONTO_TEA_DIA','DIAS_VACACIONES','ASIGNACION','N',N'LOTTT 190-194',N'CCP 18',14);

-- CCT PETROLERO - LIQUIDACION
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, CCP_Clausula, Orden)
VALUES
('CCT_PETROLERO','LIQUIDACION','PREST',N'Prestaciones','SALARIO_INTEGRAL','(ANTI_TOTAL_MESES / 12) * DIAS_PRESTACION_ANIO','ASIGNACION','N',N'LOTTT 142',NULL,10),
('CCT_PETROLERO','LIQUIDACION','VACLIQ',N'Vacaciones no gozadas','SALARIO_INTEGRAL','DIAS_VACACIONES','ASIGNACION','N',N'LOTTT 192',NULL,11),
('CCT_PETROLERO','LIQUIDACION','BONOVACLIQ',N'Bono vacacional','SALARIO_INTEGRAL','DIAS_BONO_VAC','ASIGNACION','N',N'LOTTT',NULL,12),
('CCT_PETROLERO','LIQUIDACION','SSOLIQ',N'SSO (sobre devengado)','TOTAL_ASIGNACIONES * PCT_SSO',NULL,'DEDUCCION','N',N'LOTTT',NULL,100),
('CCT_PETROLERO','LIQUIDACION','FAOVLIQ',N'FAOV (sobre devengado)','TOTAL_ASIGNACIONES * PCT_FAOV',NULL,'DEDUCCION','N',N'Ley Vivienda',NULL,101);

-- ========== CCT CONSTRUCCION - MENSUAL ==========
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, CCP_Clausula, Orden)
VALUES
('CCT_CONSTRUCCION','MENSUAL','SUELDO',N'Sueldo base','SUELDO',NULL,'ASIGNACION','S',NULL,N'Cl 44',10),
('CCT_CONSTRUCCION','MENSUAL','HE',N'Horas extras','SALARIO_HORA * (1 + RECARGO_HE)','HORAS_EXTRAS','ASIGNACION','S',N'LOTTT 175-178',NULL,11),
('CCT_CONSTRUCCION','MENSUAL','DESCTRAB',N'Descanso trabajado','SALARIO_DIARIO * (1 + RECARGO_DESCANSO)','DOMINGOS_TRABAJADOS','ASIGNACION','S',N'LOTTT',NULL,12),
('CCT_CONSTRUCCION','MENSUAL','FERIADTRAB',N'Feriado trabajado','SALARIO_DIARIO * (1 + RECARGO_FERIADO)','FERIADOS_TRABAJADOS','ASIGNACION','S',N'LOTTT',NULL,13),
('CCT_CONSTRUCCION','MENSUAL','TEA',N'TEA / Cesta ticket','MONTO_TEA_DIA','DIAS_PERIODO','ASIGNACION','N',N'LOTTT 190-194',NULL,14),
('CCT_CONSTRUCCION','MENSUAL','SSO',N'SSO (sobre devengado)','TOTAL_ASIGNACIONES * PCT_SSO',NULL,'DEDUCCION','N',N'LOTTT',NULL,100),
('CCT_CONSTRUCCION','MENSUAL','FAOV',N'FAOV (sobre devengado)','TOTAL_ASIGNACIONES * PCT_FAOV',NULL,'DEDUCCION','N',N'Ley Vivienda',NULL,101),
('CCT_CONSTRUCCION','MENSUAL','LRPE',N'LRPE','TOTAL_ASIGNACIONES * PCT_LRPE',NULL,'DEDUCCION','N',N'LOTTT',NULL,102);

-- CCT CONSTRUCCION - VACACIONES
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, CCP_Clausula, Orden)
VALUES
('CCT_CONSTRUCCION','VACACIONES','VAC',N'Vacaciones','SALARIO_INTEGRAL','DIAS_VACACIONES','ASIGNACION','S',N'LOTTT 189-203',N'Cl 44',10),
('CCT_CONSTRUCCION','VACACIONES','BONOVAC',N'Bono vacacional','SALARIO_INTEGRAL','DIAS_BONO_VAC','ASIGNACION','S',N'LOTTT',N'Cl 44',11);

-- CCT CONSTRUCCION - LIQUIDACION
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, CCP_Clausula, Orden)
VALUES
('CCT_CONSTRUCCION','LIQUIDACION','PREST',N'Prestaciones','SALARIO_INTEGRAL','(ANTI_TOTAL_MESES / 12) * DIAS_PRESTACION_ANIO','ASIGNACION','N',N'LOTTT 142',NULL,10),
('CCT_CONSTRUCCION','LIQUIDACION','VACLIQ',N'Vacaciones no gozadas','SALARIO_INTEGRAL','DIAS_VACACIONES','ASIGNACION','N',N'LOTTT 192',NULL,11),
('CCT_CONSTRUCCION','LIQUIDACION','BONOVACLIQ',N'Bono vacacional','SALARIO_INTEGRAL','DIAS_BONO_VAC','ASIGNACION','N',N'LOTTT',NULL,12),
('CCT_CONSTRUCCION','LIQUIDACION','SSOLIQ',N'SSO (sobre devengado)','TOTAL_ASIGNACIONES * PCT_SSO',NULL,'DEDUCCION','N',N'LOTTT',NULL,100),
('CCT_CONSTRUCCION','LIQUIDACION','FAOVLIQ',N'FAOV (sobre devengado)','TOTAL_ASIGNACIONES * PCT_FAOV',NULL,'DEDUCCION','N',N'Ley Vivienda',NULL,101);

-- ========== UTILIDADES (LOTTT 131): solo lo que no exista ==========
IF NOT EXISTS (SELECT 1 FROM dbo.NominaConceptoLegal WHERE Convencion = 'LOT' AND TipoCalculo = 'UTILIDADES')
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, Orden)
VALUES
('LOT','UTILIDADES','UTIL',N'Utilidades','SALARIO_DIARIO','DIAS_UTILIDADES_LOT','ASIGNACION','S',N'LOTTT 131',10),
('LOT','UTILIDADES','INCELIQ',N'INCE sobre utilidades','CUTIL * PCT_INCE_UTIL',NULL,'DEDUCCION','N',N'LOTTT',100);

IF NOT EXISTS (SELECT 1 FROM dbo.NominaConceptoLegal WHERE Convencion = 'CCT_PETROLERO' AND TipoCalculo = 'UTILIDADES')
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, CCP_Clausula, Orden)
VALUES
('CCT_PETROLERO','UTILIDADES','UTIL',N'Utilidades','SALARIO_DIARIO','DIAS_UTILIDADES_PETROLERO','ASIGNACION','S',N'LOTTT 131',N'CCP',10),
('CCT_PETROLERO','UTILIDADES','INCELIQ',N'INCE sobre utilidades','CUTIL * PCT_INCE_UTIL',NULL,'DEDUCCION','N',N'LOTTT',NULL,100);

IF NOT EXISTS (SELECT 1 FROM dbo.NominaConceptoLegal WHERE Convencion = 'CCT_CONSTRUCCION' AND TipoCalculo = 'UTILIDADES')
INSERT INTO dbo.NominaConceptoLegal (Convencion, TipoCalculo, CO_CONCEPT, NB_CONCEPTO, FORMULA, SOBRE, TIPO, BONIFICABLE, LOTTT_Articulo, CCP_Clausula, Orden)
VALUES
('CCT_CONSTRUCCION','UTILIDADES','UTIL',N'Utilidades','SALARIO_DIARIO','DIAS_UTILIDADES_CONSTRUCCION','ASIGNACION','S',N'LOTTT 131',NULL,10),
('CCT_CONSTRUCCION','UTILIDADES','INCELIQ',N'INCE sobre utilidades','CUTIL * PCT_INCE_UTIL',NULL,'DEDUCCION','N',N'LOTTT',NULL,100);

PRINT N'NominaConceptoLegal: gananciales y deducciones completos insertados.';
GO
